#!/bin/bash
#SBATCH --job-name=my_gpu_job       # Job name
#SBATCH --qos=long
#SBATCH --partition=h100             # Partition (queue) to submit to
#SBATCH --gres=gpu:1                # Request one GPU
#SBATCH --ntasks=1                  # Run on a single CPU
#SBATCH --cpus-per-task=16           # Number of CPU cores per task
#SBATCH --mem=90G                   # Job memory request
#SBATCH --time=167:59:50             # Time limit 
#SBATCH --output=output_%j.log      # Standard output and error log

module load nvhpc/24.7-mpi
module load cuda/12.5.1

source /home/pghosh/venvs/6adctmrg_Kuma/bin/activate

D=10
J2=0.275

OUTDIR=./Results_J2_nonC3CTM_${J2}/D_${D}

mkdir -p "${OUTDIR}"

python /home/pghosh/0626Kuma/main_easySwitch.py \
    --J2 "${J2}" \
    --ansatz twoc3 \
    --Ds "${D}" \
    --output-dir "${OUTDIR}"

echo "END OF JOB"

cp -r /scratch/pghosh/Working_AD_Honeycomb_July17 /home/pghosh/Data_Backup/

