#!/usr/bin/env python3
"""
plot_custom_vs_invD.py  —  Interactive / CLI figure generator
=============================================================
Plots any combination of observables vs 1/D for selected J2 values and ansätze.

Reads pre-computed analysis_results.json (generated by plot_analysis_0414.py).

Usage examples
--------------
# Order parameter for J2=0.26 and J2=0.28, both ansätze:
  python plot_custom_vs_invD.py --obs order_param --j2 0.26 0.28

# NN rank-1 correlations for all J2, only 6-tensor ansatz:
  python plot_custom_vs_invD.py --obs nn1 --ansatz 6tensors

# Energy + NNN rank-2, all J2, all ansätze, one panel per (obs, ansatz) pair:
  python plot_custom_vs_invD.py --obs energy nnn2 --j2 0.20 0.266

# Show available J2 values in the data:
  python plot_custom_vs_invD.py --list

Observable keys (--obs):
  energy          energy per site
  nn1 nn2 nn3     NN bond correlation, rank 1 / 2 / 3
  nnn1 nnn2 nnn3  NNN bond correlation, rank 1 / 2 / 3
  order_param     Néel order parameter  m

Output:
  --out  path to save PDF/PNG (default: show interactively)
  --dpi  output DPI (default 150)
"""

import argparse
import json
import os
import sys

import matplotlib
import matplotlib.gridspec as gridspec
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
from scipy.optimize import curve_fit

# ── locate JSON ───────────────────────────────────────────────────────────────
_HERE     = os.path.dirname(os.path.abspath(__file__))
_JSON_DEF = os.path.join(_HERE, 'analysis_plots', 'analysis_results.json')

# ── constants / style ─────────────────────────────────────────────────────────
ANSATZ_STYLE = {
    '6tensors': dict(color='tab:blue',   label='6-tensor',  marker='o'),
    'neel_sym' : dict(color='tab:orange', label='Néel-sym',  marker='s'),
}
RANK_CMAPS  = {1: 'Reds', 2: 'Greens', 3: 'Blues'}
RANK_LABELS = {1: 'rank 1 (most neg)', 2: 'rank 2 (mid)', 3: 'rank 3 (least neg)'}

OBS_META = {
    'energy'   : dict(label='Energy per site',          ylabel='Energy per site'),
    'nn1'      : dict(label='NN ⟨Sᵢ·Sⱼ⟩ rank 1',       ylabel='NN ⟨Sᵢ·Sⱼ⟩'),
    'nn2'      : dict(label='NN ⟨Sᵢ·Sⱼ⟩ rank 2',       ylabel='NN ⟨Sᵢ·Sⱼ⟩'),
    'nn3'      : dict(label='NN ⟨Sᵢ·Sⱼ⟩ rank 3',       ylabel='NN ⟨Sᵢ·Sⱼ⟩'),
    'nnn1'     : dict(label='NNN ⟨Sᵢ·Sⱼ⟩ rank 1',      ylabel='NNN ⟨Sᵢ·Sⱼ⟩'),
    'nnn2'     : dict(label='NNN ⟨Sᵢ·Sⱼ⟩ rank 2',      ylabel='NNN ⟨Sᵢ·Sⱼ⟩'),
    'nnn3'     : dict(label='NNN ⟨Sᵢ·Sⱼ⟩ rank 3',      ylabel='NNN ⟨Sᵢ·Sⱼ⟩'),
    'order_param': dict(label='Néel order param m',     ylabel='m'),
}

# ─────────────────────────────────────────────────────────────────────────────
# helpers
# ─────────────────────────────────────────────────────────────────────────────

def _j2_str(j2: float) -> str:
    s = f'{j2:.10f}'.rstrip('0')
    dot = s.index('.')
    if len(s) - dot - 1 < 2:
        s += '0' * (2 - (len(s) - dot - 1))
    return s


def _j2_label(j2: float) -> str:
    return f'J2={_j2_str(j2)}'


def _exp_model(D, E0, c, Dchar):
    return E0 + c * np.exp(-np.asarray(D, dtype=float) / Dchar)


def _D_colormap_rank(D_list, rank):
    Ds   = sorted(set(D_list))
    cmap = plt.get_cmap(RANK_CMAPS[rank])
    if len(Ds) == 1:
        return {Ds[0]: cmap(0.65)}
    return {D: cmap(0.30 + 0.60 * i / (len(Ds) - 1)) for i, D in enumerate(Ds)}


def _j2_colormap(j2_list):
    """Return dict j2 → color; each J2 gets a distinct hue."""
    j2s  = sorted(set(j2_list))
    cmap = plt.get_cmap('tab10')
    return {j2: cmap(i % 10) for i, j2 in enumerate(j2s)}


def _closest_j2(avail: list, target: float, tol: float = 1e-5) -> float | None:
    """Return the matching J2 in avail within tol, or None."""
    for j in avail:
        if abs(j - target) < tol:
            return j
    return None


# ─────────────────────────────────────────────────────────────────────────────
# data extraction per (obs, ansatz, j2)
# ─────────────────────────────────────────────────────────────────────────────

def _extract_series(record: dict, obs: str) -> dict | None:
    """
    Returns dict with keys: Ds, vals, errs (or None for no error), extrap_popt.
    Returns None if the observable is missing for this record.
    """
    Ds_int = record['Ds']

    if obs == 'energy':
        vals = record['energy_per_site']
        errs = None
        # keep extrap info for overlay lines
        extrap = record.get('extrap', {})
        return dict(Ds=Ds_int, vals=vals, errs=errs, extrap=extrap)

    rank_map = {'nn1': ('nn_groups', 1), 'nn2': ('nn_groups', 2), 'nn3': ('nn_groups', 3),
                'nnn1': ('nnn_groups', 1), 'nnn2': ('nnn_groups', 2), 'nnn3': ('nnn_groups', 3)}

    if obs in rank_map:
        gkey, target_rank = rank_map[obs]
        grp_data = record.get(gkey, {})
        vals, errs, Ds_out = [], [], []
        for D in Ds_int:
            d_str = str(D)
            gd = grp_data.get(d_str) or grp_data.get(D)
            if gd is None:
                continue
            try:
                idx = next(i for i, r in enumerate(gd['ranks']) if r == target_rank)
            except StopIteration:
                continue
            vals.append(gd['means'][idx])
            errs.append(gd['sterrs'][idx])
            Ds_out.append(D)
        if not Ds_out:
            return None
        return dict(Ds=Ds_out, vals=vals, errs=errs, extrap=None)

    if obs == 'order_param':
        op = record.get('order_param', {})
        Ds_out, vals, errs = [], [], []
        for D in Ds_int:
            d_str = str(D)
            entry = op.get(d_str) or op.get(D)
            if entry is None:
                continue
            Ds_out.append(D)
            vals.append(entry['m'])
            errs.append(entry['err'])
        if not Ds_out:
            return None
        return dict(Ds=Ds_out, vals=vals, errs=errs, extrap=None)

    return None


# ─────────────────────────────────────────────────────────────────────────────
# extrap overlay on energy axes
# ─────────────────────────────────────────────────────────────────────────────

def _draw_extrap_lines(ax, Ds_f, eps_f, extrap: dict, color):
    """Draw horizontal / linear / exponential extrapolation guides."""
    inv = 1.0 / Ds_f
    x_max = max(inv) * 1.15

    # 1. Horizontal dotted at E_horiz  (last-D value)
    ax.axhline(extrap['E_horiz'], color=color, lw=0.8, ls=':', alpha=0.6,
               label=f"E(D_last)={extrap['E_horiz']:.6g}")

    # 2. Linear through last 2 pts → y-intercept
    if len(Ds_f) >= 2:
        inv2   = 1.0 / Ds_f[-2:]
        coeffs = np.polyfit(inv2, eps_f[-2:], 1)
        x_lin  = np.array([0.0, inv2[0] * 1.05])
        ax.plot(x_lin, np.polyval(coeffs, x_lin),
                color=color, lw=1.0, ls='--', alpha=0.7,
                label=f"Lin-2pts → {extrap['E_lin2']:.6g}")

    # 3. Exponential fit on all Ds
    if extrap.get('exp_popt') is not None:
        E0, c, Dchar = extrap['exp_popt']
        inv_max   = inv.max() * 1.05
        inv_dense = np.linspace(1e-5, inv_max, 800)
        ax.plot(inv_dense, _exp_model(1.0 / inv_dense, E0, c, Dchar),
                color=color, lw=1.2, ls='-.', alpha=0.75,
                label=f"Exp-all → E₀={extrap['E_0']:.6g}")

    # 4. Star at (0, E_0)
    ax.plot(0, extrap['E_0'], marker='*', color=color, ms=12, zorder=7,
            markeredgewidth=0.4, markeredgecolor='k', label=f"E₀={extrap['E_0']:.6g}")


# ─────────────────────────────────────────────────────────────────────────────
# core plotting function
# ─────────────────────────────────────────────────────────────────────────────

def make_figure(
    all_results: dict,
    obs_list: list[str],
    ansatz_list: list[str],
    j2_list: list[float],
    *,
    show_extrap: bool = True,
    separate_panels: bool = False,  # True → one subplot per (obs, ansatz); False → all on one axes
    title: str | None = None,
) -> plt.Figure:
    """
    Build a matplotlib figure.

    separate_panels=False  →  every selected series on the same axes
    separate_panels=True   →  grid: rows=obs, cols=ansatz (each panel one observable+ansatz,
                               lines per J2)
    """
    # Collect available J2s in the data for the chosen ansätze
    avail_j2 = sorted(set(
        v['j2'] for v in all_results.values()
        if v['ansatz'] in ansatz_list
    ))

    # Resolve J2 list (match with tolerance)
    if j2_list:
        resolved = []
        for t in j2_list:
            m = _closest_j2(avail_j2, t)
            if m is None:
                print(f"  WARNING: J2={t} not found in data (available: {avail_j2})")
            else:
                resolved.append(m)
        if not resolved:
            raise ValueError("No valid J2 values after matching.")
        selected_j2s = resolved
    else:
        selected_j2s = avail_j2   # all

    j2_colors = _j2_colormap(selected_j2s)

    # ── build panel grid ──────────────────────────────────────────────────────
    if separate_panels:
        nrows, ncols = len(obs_list), len(ansatz_list)
        fig, axes_grid = plt.subplots(
            nrows, ncols,
            figsize=(6 * ncols, 5 * nrows),
            squeeze=False,
        )
    else:
        fig, ax_single = plt.subplots(figsize=(9, 6))
        # Build a dummy grid so the loop below is uniform
        axes_grid = [[ax_single] * len(ansatz_list)] * len(obs_list)

    # ── populate panels ───────────────────────────────────────────────────────
    for row, obs in enumerate(obs_list):
        obs_m = OBS_META[obs]

        for col, ansatz in enumerate(ansatz_list):
            ax = axes_grid[row][col]
            ast = ANSATZ_STYLE[ansatz]

            for j2 in selected_j2s:
                # Find the matching record
                rec = next(
                    (v for v in all_results.values()
                     if v['ansatz'] == ansatz and abs(v['j2'] - j2) < 1e-5),
                    None
                )
                if rec is None:
                    continue

                series = _extract_series(rec, obs)
                if series is None:
                    continue

                Ds_f  = np.array(series['Ds'], dtype=float)
                vals  = np.array(series['vals'])
                errs  = series['errs']
                inv   = 1.0 / Ds_f

                # Choose color strategy:
                # • separate_panels → color by J2 (different J2s are the lines)
                # • single panel    → color by (ansatz, obs) pair if multi-ansatz/obs,
                #                     otherwise color by J2
                if separate_panels:
                    line_color = j2_colors[j2]
                    line_label = _j2_label(j2)
                else:
                    # In merged view color by ansatz when multi-ansatz, else by J2
                    if len(ansatz_list) > 1:
                        base_color = ast['color']
                        # blend towards j2 index slightly
                        line_color = base_color
                        line_label = f"{ast['label']}  {_j2_label(j2)}"
                    else:
                        line_color = j2_colors[j2]
                        line_label = _j2_label(j2)
                    # Distinguish obs by linestyle
                    obs_ls = ['-', '--', '-.', ':'][obs_list.index(obs) % 4]

                mk = ast['marker']

                if errs is not None:
                    eb = ax.errorbar(
                        inv, vals, yerr=errs,
                        fmt=mk, color=line_color, ms=6,
                        capsize=3, elinewidth=0.8, lw=1.0 if separate_panels else 0,
                        label=line_label, alpha=0.85,
                    )
                    # connect points with a line
                    if separate_panels:
                        ax.plot(inv, vals, '-', color=line_color, lw=0.9, alpha=0.5)
                else:
                    ax.plot(inv, vals, f'{mk}-', color=line_color, ms=6, lw=1.2,
                            label=line_label, alpha=0.85)

                # Extrapolation guides (energy only or if requested)
                if show_extrap and obs == 'energy' and series['extrap']:
                    _draw_extrap_lines(ax, Ds_f, vals, series['extrap'], line_color)

            # ── axes cosmetics ─────────────────────────────────────────────
            ax.set_xlabel('1/D', fontsize=11)
            ax.set_ylabel(obs_m['ylabel'], fontsize=11)
            if separate_panels:
                ax.set_title(f"{obs_m['label']}  —  {ast['label']}", fontsize=10)
            ax.xaxis.set_major_formatter(ticker.FormatStrFormatter('%.4g'))
            ax.yaxis.set_major_formatter(ticker.FormatStrFormatter('%.5g'))
            ax.set_xlim(left=-0.01)
            ax.legend(fontsize=7, ncol=2)
            ax.tick_params(labelsize=9)

    # ── figure-level title ────────────────────────────────────────────────────
    obs_str    = ', '.join(OBS_META[o]['label'] for o in obs_list)
    ansatz_str = ', '.join(ANSATZ_STYLE[a]['label'] for a in ansatz_list)
    j2_str     = ', '.join(_j2_label(j) for j in selected_j2s) if len(selected_j2s) <= 6 \
                 else f'{len(selected_j2s)} J2 values'
    auto_title = f"{obs_str}  |  {ansatz_str}  |  {j2_str}"
    fig.suptitle(title or auto_title, fontsize=10, wrap=True)
    plt.tight_layout(rect=[0, 0, 1, 0.96])

    return fig


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument('--json', default=_JSON_DEF, metavar='PATH',
                   help='Path to analysis_results.json')
    p.add_argument('--obs', nargs='+',
                   choices=list(OBS_META.keys()),
                   default=['order_param'],
                   metavar='OBS',
                   help='Observable(s) to plot: ' + ' '.join(OBS_META.keys()))
    p.add_argument('--ansatz', nargs='+',
                   choices=['6tensors', 'neel_sym', 'both'],
                   default=['both'],
                   metavar='ANSATZ',
                   help='Ansatz filter: 6tensors | neel_sym | both')
    p.add_argument('--j2', nargs='*', type=float, default=[],
                   metavar='J2',
                   help='J2 value(s) to include (default: all available)')
    p.add_argument('--separate', action='store_true',
                   help='One subplot per (obs × ansatz) combination')
    p.add_argument('--no-extrap', dest='extrap', action='store_false',
                   help='Suppress extrapolation lines on energy plots')
    p.add_argument('--title', default=None,
                   help='Custom figure title')
    p.add_argument('--out', default=None, metavar='FILE',
                   help='Save to file (PDF/PNG/SVG). If omitted, display interactively.')
    p.add_argument('--dpi', type=int, default=150)
    p.add_argument('--list', action='store_true',
                   help='List available J2 values and ansätze, then exit.')
    return p


def main():
    args = _build_parser().parse_args()

    # Load JSON
    if not os.path.exists(args.json):
        sys.exit(
            f"ERROR: analysis_results.json not found at {args.json}\n"
            "Run plot_analysis_0414.py first to generate it."
        )
    with open(args.json) as f:
        all_results = json.load(f)

    # --list
    if args.list:
        ansatze = sorted(set(v['ansatz'] for v in all_results.values()))
        print("Available ansätze:", ansatze)
        for ans in ansatze:
            j2s = sorted(set(v['j2'] for v in all_results.values() if v['ansatz'] == ans))
            print(f"  {ans}: J2 = {[round(j, 8) for j in j2s]}")
        sys.exit(0)

    # Resolve ansatz list
    ansatz_list: list[str] = []
    for a in args.ansatz:
        if a == 'both':
            ansatz_list = ['6tensors', 'neel_sym']
            break
        ansatz_list.append(a)
    ansatz_list = list(dict.fromkeys(ansatz_list))  # deduplicate, preserve order

    # Build figure
    if args.out is None:
        matplotlib.use('TkAgg')   # interactive
    else:
        matplotlib.use('Agg')

    fig = make_figure(
        all_results,
        obs_list=args.obs,
        ansatz_list=ansatz_list,
        j2_list=args.j2,
        show_extrap=args.extrap,
        separate_panels=args.separate,
        title=args.title,
    )

    if args.out:
        fig.savefig(args.out, dpi=args.dpi, bbox_inches='tight')
        print(f"Saved: {args.out}")
    else:
        plt.show()


if __name__ == '__main__':
    main()
