#!/bin/bash
#SBATCH -q academic
#SBATCH --partition academic
#SBATCH -e ./job-%N-%j.error
#SBATCH -o ./job-%N-%j.out
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 25
#SBATCH --time 1-00:06:00
#SBATCH --mem 140G


echo "***** START OF JOB ***** "

module purge
module load gcc
#module load julia/1.12

echo STARTING AT `date`

source /home/chye/venvs/6adctmrg/bin/activate
python /home/chye/0507core/recompute_obs.py --J2 0.27 --file /home/chye/0507core/27_D9_unfinished.pt

echo FINISHED at `date`

echo " ***** END OF JOB ***** "

