#!/usr/bin/env bash
#SBATCH --qos=normal
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=40G
#SBATCH --time=71:59:50
#SBATCH --exclude=i39
#SBATCH -o slurm_logs/plaq-refine-%N-%j.out
#SBATCH -e slurm_logs/plaq-refine-%N-%j.error

set -euo pipefail
module load gcc/11.3.0
module load cuda/11.8.0
source /home/chye/venvs/6adctmrg_Izar/bin/activate
bash ./run_plaq_refinement.sh
