#!/bin/bash
##SBATCH --qos long
#SBATCH --partition gpu
#SBATCH -e ./job-%N-%j.error
#SBATCH -o ./job-%N-%j.out
#SBATCH --gres=gpu:1                # Request one GPU
#SBATCH --ntasks=1                  # Run on a single CPU
#SBATCH --cpus-per-task=1           # Number of CPU cores per task
#SBATCH --mem=40G                   # Job memory request
#SBATCH --time=71:59:50             # Time limit
#SBATCH --exclude=i39

echo "***** START OF JOB ***** "
module load gcc/11.3.0
module load cuda/11.8.0
echo STARTING AT `date`

source /home/chye/venvs/6adctmrg_Izar/bin/activate
python /home/chye/0801core/main_colum.py --J2 0.30 --Ds 8

echo FINISHED at `date`
echo " ***** END OF JOB ***** "
cp -r ./  /home/chye/0801core/